from typing import Protocol

from flat_finder.users.model import User


class UserDAO(Protocol):
    def get_by_id(self, user_id: int) -> User | None: ...
    def get_by_username(self, username: str) -> User | None: ...
    def create(self, username: str) -> User: ...
    def update_ntfy_topic(self, user_id: int, topic: str | None) -> None: ...
    def get_all_with_ntfy(self) -> list[User]: ...
