from typing import Protocol

from flat_finder.zones.model import Zone


class ZoneDAO(Protocol):
    def get_by_user(self, user_id: int) -> list[Zone]: ...
    def get_all(self) -> list[Zone]: ...
    def get_by_id(self, zone_id: int) -> Zone | None: ...
    def create(  # noqa: PLR0913
        self,
        user_id: int,
        name: str,
        geometry: str,
        centroid_lat: float,
        centroid_lng: float,
        covering_radius_km: float,
        rightmove_id: str | None,
        openrent_term: str | None,
        color_index: int,
    ) -> Zone: ...
    def update(self, zone_id: int, **kwargs: object) -> None: ...
    def delete(self, zone_id: int) -> None: ...


class ListingZoneDAO(Protocol):
    def link(self, listing_id: str, zone_id: int) -> None: ...
    def get_zone_ids_for_listing(self, listing_id: str) -> list[int]: ...
    def get_listing_ids_for_zones(self, zone_ids: list[int]) -> list[str]: ...
    def delete_for_listings(self, listing_ids: list[str]) -> None: ...
