from typing import Protocol

from flat_finder.pois.model import POI


class POIDAO(Protocol):
    def get_by_user(self, user_id: int) -> list[POI]: ...
    def get_by_id(self, poi_id: int) -> POI | None: ...
    def get_all(self) -> list[POI]: ...
    def create(self, user_id: int, name: str, lat: float, lng: float, color_index: int) -> POI: ...
    def delete(self, poi_id: int) -> None: ...


class POICommuteDAO(Protocol):
    def upsert(self, listing_id: str, poi_id: int, commute_mins: int) -> None: ...
    def get_for_listings(self, listing_ids: list[str]) -> dict[str, dict[int, int]]: ...
    def get_listings_missing_poi(self, poi_id: int) -> list[dict]: ...
    def delete_for_listings(self, listing_ids: list[str]) -> None: ...
