from typing import Any, Protocol

from flat_finder.listings.model import Listing, ListingState


class ListingDAO(Protocol):
    def insert(self, listing: dict[str, Any]) -> bool: ...
    def get_all_with_state(self, user_id: int, zone_ids: list[int]) -> list[dict[str, Any]]: ...
    def get_by_id(self, listing_id: str) -> Listing | None: ...
    def get_listings_in_zone_polygon(self, geometry_geojson: str) -> list[Listing]: ...
    def archive_old(self, days: int) -> int: ...


class ListingStateDAO(Protocol):
    def get(self, user_id: int, listing_id: str) -> ListingState | None: ...
    def upsert(self, user_id: int, listing_id: str, updates: dict[str, Any]) -> ListingState: ...
    def delete_for_listings(self, listing_ids: list[str]) -> None: ...
